
# Requirements for the project
[project]
name = "example_project"
version = "0.1.0"
description = "An example project to demonstrate pyproject.toml usage"
authors = [
    { name = "John Doe", email = "" },
]
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "orjson>=3.8.0",
]